### ISSUE TITLE
Implement Haikuporter recipe syntax highlighting

### ISSUE THREAD

**Issue by extrowerk** [KapiX/Koder#3]
Like Pe does, it is really helpful to know, what is a real keyword, and wich not.

**Comment by waddlesplash** [comment]
Seems fixed?

**Comment by KapiX** [comment]
The issue is I think lack of highlighting for `app:`, `cmd:` etc. That would require modifying bash lexer, which I didn't get around doing yet.

**Comment by KapiX** [comment]
The most important part of this issue is solved (highlighting env vars, built-in vars and shell scriptlets). Highlighting for `app:`, `cmd:`, etc., variables and comments inside strings will require more invasive changes to the lexer. Additionally it has weird distinction between $ and ${} vars. However, Pe didn't support that either, so I consider this fixed and the rest goes to the post-1.0 backlog.
