### ISSUE TITLE
Change "Go to line..." keycombo, add shortcut

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#31]
ALT+G is normally used for "Find next". I suggest Pe's ALT+, instead and change or maybe even remove the keycombo for "Koder preferences...". Once you've configured Koder, you probably don't need them as often.

The "Go to line..." could also be available with a double-click anywhere on the line number column (and when clicking on the "line&column" in the status bar, if that is to be implemented).

**Comment by KapiX** [comment]
I can't add a double-click shortcut because margins can be either click sensitive or click insensitive. When they are insensitive they don't report mouse events, but you can use them to select lines. When they are sensitive, line selection doesn't work, but events are reported. I think it's more important to have line selection.
Status bar shortcut will be implemented together with status bar

**Comment by humdingerb** [comment]
Sounds like the right decision. Thanks!
