### ISSUE TITLE
Add more navigation keyboard shortcuts

### ISSUE THREAD

**Issue by anevilyak** [KapiX/Koder#51]
It would be nice to have some shortcuts for navigating to the beginning/end of a document. Pe implements these as cmd+home/end, as do various other graphical editors I use.

**Comment by KapiX** [comment]
So, Scintilla supports this out of the box:
https://sourceforge.net/p/scintilla/code/ci/default/tree/src/KeyMap.cxx#l106
but somebody designing BeAPI thought it's a good idea to eat every single key combo with Cmd in it, so Scintilla is not even aware when it's hit :)
https://www.haiku-os.org/legacy-docs/bebook/BView.html#BView_KeyDown

I have a solution for this but it's ridiculous :) Should be fixed with next Scintilla release.

**Comment by KapiX** [comment]
Fixed in https://sourceforge.net/p/scintilla/haiku/ci/3d49914b318b1288c075ebdcb6d5f782e94f7ac6/.

It's not as ridiculous as I thought it would be, but it required changes to Scintilla itself.
