### ISSUE TITLE
Crash when viewing "Page source" of Haiku site

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#74]
Koder crashes when it is set as default editor and you choose "Show | Page source" in WebPositive when viewing https://www.haiku-os.org/ .

Can't attach any file with the browsers I have...

Debug report: http://ix.io/1udW
The site's HTML: https://0x0.st/s081.html

This is with a current Koder master: cb7800bf6eaf053164cf2d5e00848d334a86e8ff

**Comment by KapiX** [comment]
If I'm seeing right, the character on which `towlower` crashed is `__c: 128269`... (drums)... that is an emoji!
http://www.codetable.net/decimal/128269
It appears `towlower` does not like emojis :(

The issue is in the standard library, there is nothing I can do about it. It should probably be filed in haikuports repo for GCC or even in the main bugtracker if it happens on linux too.
Reproducer:
```c++
#include <cwctype>

int main() {
    wint_t glassEmoji = 128269;
    wint_t lower = towlower(glassEmoji); // crash
    return 0;
}
```

**Comment by humdingerb** [comment]
Thanks for the investigation. I don't find the code for that "Left-Pointing Magnifying Glass" in the main page source though. I looked for hex 1f50d and dec 128269.

**Comment by KapiX** [comment]
It's on the search button.

**Comment by humdingerb** [comment]
Oh, OK, it's not inserted as hex/dec Unicode, but... I dunno what you call it... as character(?).
Maybe we should change it to an image, considering that Haiku can't display it...
